name: Maven Version Bump

on:
  push:
    branches:
      - "release/**"

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v2
      with:
          # Create changelog needs the entire history of the project to generate. The script handles everything else.
          fetch-depth: 0

    - name: Bump Version main
      id: bump-main
      uses: E-Health/maven-version-bump-action@v4.3
      with:
        github-token: ${{ secrets.github_token }}
        version-prefix: pre-

    - name: Bump Version deploy
      id: bump-deploy
      uses: E-Health/maven-version-bump-action@v4.3
      with:
        github-token: ${{ secrets.github_token }}
        pom-path: ./pom-deploy.xml
        version-prefix: dep-

    - name: Create changelog
      uses: srepollock/changelog-generator-action@master
      with:
        REPO_NAME: ${{ github.repository	}}
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: '/CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'