name: Generate and publish gh-pages
on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: 13
    - name: Generate docs with Maven
      run: mvn javadoc:javadoc

    - name: Deploy Docs 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: target/site/apidocs # The folder the action should deploy