name: Java Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13
      uses: actions/setup-java@v2.1.0
      with:
        java-version: 13
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true --file pom-deploy.xml
    - name: Deploy to Github Package Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B -e -Dmaven.wagon.http.pool=false -Dmaven.test.skip=true -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/dermatologist/ckblib --settings settings.xml clean deploy --file pom-deploy.xml